DELIMITER $$
CREATE EVENT `DeleteDataOlder8Hours`
ON SCHEDULE
EVERY 1 HOUR 
DO BEGIN
   DELETE FROM sensor1 WHERE timestamp < (CURRENT_TIMESTAMP - INTERVAL 8 HOUR);
   DELETE FROM sensor2 WHERE timestamp < (CURRENT_TIMESTAMP - INTERVAL 8 HOUR);
   DELETE FROM sensor3 WHERE timestamp < (CURRENT_TIMESTAMP - INTERVAL 8 HOUR);
   DELETE FROM sensor4 WHERE timestamp < (CURRENT_TIMESTAMP - INTERVAL 8 HOUR);
   DELETE FROM sensor5 WHERE timestamp < (CURRENT_TIMESTAMP - INTERVAL 8 HOUR);
   DELETE FROM sensor6 WHERE timestamp < (CURRENT_TIMESTAMP - INTERVAL 8 HOUR);
   DELETE FROM sensor7 WHERE timestamp < (CURRENT_TIMESTAMP - INTERVAL 8 HOUR);
   DELETE FROM sensor8 WHERE timestamp < (CURRENT_TIMESTAMP - INTERVAL 8 HOUR);

END$$
DELIMITER ;

